var gamePattern = [];   //stores the pattern of color generated by the program
var userClickedPattern = [];    //stores the pattern of color clicked by the user
var level = 0;
var buttonColors = ["red", "blue", "green", "yellow"];
var started = false;

//generates a random number between [0,3]
function nextSequence(){
    userClickedPattern.length = 0;
    var num = Math.random();
    num*=10;
    num = Math.floor(num);    
    num%=4;
    //passes a random color from the "buttonColors" list to gamePattern (helps in deciding the order of colors to be clicked by the user)
    var randomNumber = num;
    var randomChosenColor = buttonColors[randomNumber];
    gamePattern.push(randomChosenColor);

    //plays sound + animation of the randomly chosen color by the above program-lines (telling user about the randomly chosen color)
    playSound(randomChosenColor);
    $("."+randomChosenColor).animate({opacity:0.5});
    var buttonTimeout = setTimeout(function(){
        $("."+randomChosenColor).animate({opacity:1});
    }, 500);
}

//plays sound when a button is clicked
function playSound(key){
    switch(key){
        case "red":
            var redAudio = new Audio("./sounds/red.mp3");
            redAudio.play();
            break;
        case "blue":
            var blueAudio = new Audio("./sounds/blue.mp3");
            blueAudio.play();
            break;
        case "green":
            var greenAudio = new Audio("./sounds/green.mp3");
            greenAudio.play();
            break;
        case "yellow":
            var yellowAudio = new Audio("./sounds/yellow.mp3");
            yellowAudio.play();
            break;
        case "wrong": 
            var wrongAudio = new Audio("./sounds/wrong.mp3");
            wrongAudio.play();
            break;
    }
}
//gives shadow around button when pressed
function animatePress(currentColor){
    $("."+currentColor).addClass("pressed");
    setTimeout(function (){
        $("."+currentColor).removeClass("pressed");
    }, 100);
}

//waits for a key to be pressed to start the game
$(document).keypress(function(){
    if(!started){
        gamePattern.length=0;
        level=0;
        started = true;
        nextSequence();
        level++;
        setTimeout(function(){$("h1").text("Level "+level);}, 100);
    }
})

//checks the click and matches with gamePattern
function checkAnswer(currentLevel){
    if(gamePattern[currentLevel] !== userClickedPattern[currentLevel]){
        $("body").addClass("game-over");
        setTimeout(function(){
            $("body").removeClass("game-over");
        }, 200);
        $("h1").text("Game Over, Press Any Key to Restart");
        playSound("wrong");

        gamePattern.length=0;
        userClickedPattern.length=0;
        level=0;
        started=false;
        return;
    }
    if(userClickedPattern.length === gamePattern.length){
        setTimeout(nextSequence, 1000);
        level++;
        setTimeout(function(){$("h1").text("Level "+level);}, 1100);
    }

}

//confirming the user clicked button with sound + animation
$(".btn").click(function(){
    if(!started) return;

    var userChosenColor = this.id;
    userClickedPattern.push(userChosenColor);

    var currentIndex = userClickedPattern.length-1;
    playSound(userChosenColor);
    animatePress(userChosenColor);
    checkAnswer(currentIndex);
});